name: Deploy to VPS

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH access
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy via rsync
        run: |
            echo "VPS_HOST=${{ vars.VPS_HOST }}"
            #echo "VPS_DEST_PATH=${{ secrets.VPS_DEST_PATH }}"
            rsync -avz --delete \
              -e "ssh -o StrictHostKeyChecking=no" \
              ./ ${{ secrets.VPS_USER }}@${{ vars.VPS_HOST }}:${{ secrets.VPS_DEST_PATH }}
